/**
 * @file fuzz_save_loader.cpp
 * @brief libFuzzer harness for the save loader (aoc::save::loadGame).
 *
 * The loader parses fully attacker-controllable binary input; this drives
 * it end-to-end on fuzzer-generated bytes. The invariant is only "never
 * crash / never OOM / never UB" -- any ErrorCode (including Ok) is fine.
 *
 * Build (not part of the normal build; needs clang + the fuzzer runtime):
 *   AOC_BUILD_FUZZERS=ON with a clang toolchain, then
 *   ./build/<preset>/fuzz_save_loader -max_len=65536 tests/data/saves
 *
 * loadGame takes a path, so each input is written to a temp file. Slower
 * than an in-memory entry point, but it exercises the real public surface
 * (including the file-size/read handling) with zero production changes.
 */

#include "aoc/core/Random.hpp"
#include "aoc/game/GameState.hpp"
#include "aoc/map/FogOfWar.hpp"
#include "aoc/map/HexGrid.hpp"
#include "aoc/save/Serializer.hpp"
#include "aoc/simulation/diplomacy/DiplomacyState.hpp"
#include "aoc/simulation/resource/EconomySimulation.hpp"
#include "aoc/simulation/turn/TurnManager.hpp"

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <string>

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
    // A per-process temp file, reused across iterations.
    static const std::string path = [] {
        std::string p = "fuzz_save_input.bin";
        return p;
    }();

    {
        std::ofstream out(path, std::ios::binary | std::ios::trunc);
        if (!out.good()) { return 0; }
        out.write(reinterpret_cast<const char*>(data),
                  static_cast<std::streamsize>(size));
    }

    aoc::game::GameState gameState;
    aoc::map::HexGrid grid;
    aoc::sim::TurnManager turnManager;
    aoc::sim::EconomySimulation economy;
    aoc::sim::DiplomacyManager diplomacy;
    aoc::map::FogOfWar fogOfWar;
    aoc::Random rng(1u);

    // Return value intentionally ignored: we only care that no input
    // crashes, over-allocates, or triggers UB.
    static_cast<void>(aoc::save::loadGame(path, gameState, grid, turnManager,
                                          economy, diplomacy, fogOfWar, rng));
    return 0;
}
